package com.superkeyword;

public class AsciiSample {
	public static void main(String[]args) {
		//Capital letters
		int a = 'A';
		System.out.println(a);
		int b = 'B';
		System.out.println(b);
		int c = 'C';
		System.out.println(c);
		int d = 'D';
		System.out.println(d);
		int e = 'E';
		System.out.println(e);
		int f ='F';
		System.out.println(f);
		int g = 'G';
		System.out.println(g);
		int h = 'H';
		System.out.println(h);
		int i = 'I';
		System.out.println(i);
		int j = 'J';
		System.out.println(j);
		int k = 'K';
		System.out.println(k);
		int l = 'L';
		System.out.println(l);
		int m = 'M';
		System.out.println(m);
		int n ='N';
		System.out.println(n);
		int o = 'O';
		System.out.println(o);
		int p = 'P';
		System.out.println(p);
		int q = 'Q';
		System.out.println(q);
		int r = 'R';
		System.out.println(r);
		int s = 'S';
		System.out.println(s);
		int t = 'T';
		System.out.println(t);
		int u = 'U';
		System.out.println(u);
		int v = 'V';
		System.out.println(v);
		int w='W';
		System.out.println(w);
		int x = 'X';
		System.out.println(x);
		int y = 'Y';
		System.out.println(y);
		int z = 'Z';
		System.out.println(z);
		
		//small letters
		int aa = 'a';
		System.out.println(aa);
		int ab = 'b';
		System.out.println(ab);
		int ac = 'c';
		System.out.println(ac);
		int ad ='d';
		System.out.println(ad);
		int ae ='e';
		System.out.println(ae);
		int af = 'f';
		System.out.println(af);
		int ag = 'g';
		System.out.println(ag);
		int ah = 'h';
		System.out.println(ah);
		int ai = 'i';
		System.out.println(ai);
		int aj = 'j';
		System.out.println(aj);
		int ak = 'k';
		System.out.println(ak);
		int al = 'l';
		System.out.println(al);
		int am = 'm';
		System.out.println(am);
		int an = 'n';
		System.out.println(an);
		int ao = 'o';
		System.out.println(ao);
		int ap = 'p';
		System.out.println(ap);
		int aq = 'q';
		System.out.println(aq);
		int ar = 'r';
		System.out.println(ar);
		int as = 's';
		System.out.println(as);
		int at = 't';
		System.out.println(at);
		int au = 'u';
		System.out.println(au);
		int av = 'v';
		System.out.println(av);
		int aw = 'w';
		System.out.println(aw);
		int ax = 'x';
		System.out.println(ax);
		int ay = 'y';
		System.out.println(ay);
		int az = 'z';
		System.out.println(az);
		
	}
}
